/**
 *This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.
 */
package com.dotta.forgotpassword.controller;

import com.dotta.forgotpassword.ForgotPassword;
import java.lang.String;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/forgotPassword")
public class ForgotPasswordController {

    @Autowired
    private ForgotPassword forgotPassword;

    @RequestMapping(value = "/password", produces = "application/json", method = RequestMethod.GET)
    public String getPassword() {
        return forgotPassword.getPassword();
    }

    @RequestMapping(value = "/sendEmail", produces = "application/json", method = RequestMethod.GET)
    public String sendEmail(@RequestParam(value = "toEmailAddress", required = false) String toEmailAddress) {
        return forgotPassword.sendEmail(toEmailAddress);
    }
}
