/*Copyright (c) 2018-2019 medidesign.co.uk All Rights Reserved.
 This software is the confidential and proprietary information of medidesign.co.uk You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medidesign.co.uk*/
package com.dotta.medidata.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AddSymptomRequest implements Serializable {


    @JsonProperty("patient_id")
    @NotNull
    private Integer patientId;

    @JsonProperty("allergy_id")
    @NotNull
    private Integer allergyId;

    @JsonProperty("symptom_id")
    @NotNull
    private Integer symptomId;

    @JsonProperty("result")
    @NotNull
    private Integer result;

    @JsonProperty("session_id")
    @NotNull
    private Integer sessionId;

    @JsonProperty("data_source")
    @NotNull
    private Integer dataSource;

    @JsonProperty("current_status")
    @NotNull
    private Integer currentStatus;

    public Integer getPatientId() {
        return this.patientId;
    }

    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    public Integer getAllergyId() {
        return this.allergyId;
    }

    public void setAllergyId(Integer allergyId) {
        this.allergyId = allergyId;
    }

    public Integer getSymptomId() {
        return this.symptomId;
    }

    public void setSymptomId(Integer symptomId) {
        this.symptomId = symptomId;
    }

    public Integer getResult() {
        return this.result;
    }

    public void setResult(Integer result) {
        this.result = result;
    }

    public Integer getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    public Integer getDataSource() {
        return this.dataSource;
    }

    public void setDataSource(Integer dataSource) {
        this.dataSource = dataSource;
    }

    public Integer getCurrentStatus() {
        return this.currentStatus;
    }

    public void setCurrentStatus(Integer currentStatus) {
        this.currentStatus = currentStatus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AddSymptomRequest)) return false;
        final AddSymptomRequest addSymptomRequest = (AddSymptomRequest) o;
        return Objects.equals(getPatientId(), addSymptomRequest.getPatientId()) &&
                Objects.equals(getAllergyId(), addSymptomRequest.getAllergyId()) &&
                Objects.equals(getSymptomId(), addSymptomRequest.getSymptomId()) &&
                Objects.equals(getResult(), addSymptomRequest.getResult()) &&
                Objects.equals(getSessionId(), addSymptomRequest.getSessionId()) &&
                Objects.equals(getDataSource(), addSymptomRequest.getDataSource()) &&
                Objects.equals(getCurrentStatus(), addSymptomRequest.getCurrentStatus());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPatientId(),
                getAllergyId(),
                getSymptomId(),
                getResult(),
                getSessionId(),
                getDataSource(),
                getCurrentStatus());
    }
}