/*Copyright (c) 2018-2019 medidesign.co.uk All Rights Reserved.
 This software is the confidential and proprietary information of medidesign.co.uk You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medidesign.co.uk*/
package com.dotta.medidata.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ListCliniciansforPatientResponse implements Serializable {


    @ColumnAlias("user_id")
    private Integer userId;

    @ColumnAlias("clinician_title")
    private String clinicianTitle;

    @ColumnAlias("clinician_first_name")
    private String clinicianFirstName;

    @ColumnAlias("clinician_last_name")
    private String clinicianLastName;

    @ColumnAlias("relationship")
    private String relationship;

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getClinicianTitle() {
        return this.clinicianTitle;
    }

    public void setClinicianTitle(String clinicianTitle) {
        this.clinicianTitle = clinicianTitle;
    }

    public String getClinicianFirstName() {
        return this.clinicianFirstName;
    }

    public void setClinicianFirstName(String clinicianFirstName) {
        this.clinicianFirstName = clinicianFirstName;
    }

    public String getClinicianLastName() {
        return this.clinicianLastName;
    }

    public void setClinicianLastName(String clinicianLastName) {
        this.clinicianLastName = clinicianLastName;
    }

    public String getRelationship() {
        return this.relationship;
    }

    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ListCliniciansforPatientResponse)) return false;
        final ListCliniciansforPatientResponse listCliniciansforPatientResponse = (ListCliniciansforPatientResponse) o;
        return Objects.equals(getUserId(), listCliniciansforPatientResponse.getUserId()) &&
                Objects.equals(getClinicianTitle(), listCliniciansforPatientResponse.getClinicianTitle()) &&
                Objects.equals(getClinicianFirstName(), listCliniciansforPatientResponse.getClinicianFirstName()) &&
                Objects.equals(getClinicianLastName(), listCliniciansforPatientResponse.getClinicianLastName()) &&
                Objects.equals(getRelationship(), listCliniciansforPatientResponse.getRelationship());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUserId(),
                getClinicianTitle(),
                getClinicianFirstName(),
                getClinicianLastName(),
                getRelationship());
    }
}