/*Copyright (c) 2018-2019 medidesign.co.uk All Rights Reserved.
 This software is the confidential and proprietary information of medidesign.co.uk You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medidesign.co.uk*/
package com.dotta.medidata.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class MedicsWithPatientsResponse implements Serializable {


    @ColumnAlias("title")
    private String title;

    @ColumnAlias("first_name")
    private String firstName;

    @ColumnAlias("last_name")
    private String lastName;

    @ColumnAlias("address1")
    private String address1;

    @ColumnAlias("address2")
    private String address2;

    @ColumnAlias("address3")
    private String address3;

    @ColumnAlias("postcode")
    private String postcode;

    @ColumnAlias("date_of_birth")
    private Date dateOfBirth;

    @ColumnAlias("health_number")
    private String healthNumber;

    @ColumnAlias("patient_id")
    private Integer patientId;

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getAddress3() {
        return this.address3;
    }

    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getHealthNumber() {
        return this.healthNumber;
    }

    public void setHealthNumber(String healthNumber) {
        this.healthNumber = healthNumber;
    }

    public Integer getPatientId() {
        return this.patientId;
    }

    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof MedicsWithPatientsResponse)) return false;
        final MedicsWithPatientsResponse medicsWithPatientsResponse = (MedicsWithPatientsResponse) o;
        return Objects.equals(getTitle(), medicsWithPatientsResponse.getTitle()) &&
                Objects.equals(getFirstName(), medicsWithPatientsResponse.getFirstName()) &&
                Objects.equals(getLastName(), medicsWithPatientsResponse.getLastName()) &&
                Objects.equals(getAddress1(), medicsWithPatientsResponse.getAddress1()) &&
                Objects.equals(getAddress2(), medicsWithPatientsResponse.getAddress2()) &&
                Objects.equals(getAddress3(), medicsWithPatientsResponse.getAddress3()) &&
                Objects.equals(getPostcode(), medicsWithPatientsResponse.getPostcode()) &&
                Objects.equals(getDateOfBirth(), medicsWithPatientsResponse.getDateOfBirth()) &&
                Objects.equals(getHealthNumber(), medicsWithPatientsResponse.getHealthNumber()) &&
                Objects.equals(getPatientId(), medicsWithPatientsResponse.getPatientId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTitle(),
                getFirstName(),
                getLastName(),
                getAddress1(),
                getAddress2(),
                getAddress3(),
                getPostcode(),
                getDateOfBirth(),
                getHealthNumber(),
                getPatientId());
    }
}