/*Copyright (c) 2018-2019 medidesign.co.uk All Rights Reserved.
 This software is the confidential and proprietary information of medidesign.co.uk You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medidesign.co.uk*/
package com.dotta.medidata.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.hibernate.Hibernate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.data.util.DaoUtils;
import com.wavemaker.runtime.file.model.Downloadable;

import com.dotta.medidata.Allergies;
import com.dotta.medidata.CompoundsAllergies;
import com.dotta.medidata.SubstitutesAllergies;
import com.dotta.medidata.SurveyAndTestData;
import com.dotta.medidata.SynonymAllergies;


/**
 * ServiceImpl object for domain model class Allergies.
 *
 * @see Allergies
 */
@Service("medidata.AllergiesService")
@Validated
public class AllergiesServiceImpl implements AllergiesService {

    private static final Logger LOGGER = LoggerFactory.getLogger(AllergiesServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("medidata.CompoundsAllergiesService")
    private CompoundsAllergiesService compoundsAllergiesService;

    @Lazy
    @Autowired
    @Qualifier("medidata.SubstitutesAllergiesService")
    private SubstitutesAllergiesService substitutesAllergiesService;

    @Lazy
    @Autowired
    @Qualifier("medidata.SurveyAndTestDataService")
    private SurveyAndTestDataService surveyAndTestDataService;

    @Lazy
    @Autowired
    @Qualifier("medidata.SynonymAllergiesService")
    private SynonymAllergiesService synonymAllergiesService;

    @Autowired
    @Qualifier("medidata.AllergiesDao")
    private WMGenericDao<Allergies, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Allergies, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "medidataTransactionManager")
    @Override
    public Allergies create(Allergies allergies) {
        LOGGER.debug("Creating a new Allergies with information: {}", allergies);

        List<CompoundsAllergies> compoundsAllergieses = allergies.getCompoundsAllergieses();
        List<SubstitutesAllergies> substitutesAllergieses = allergies.getSubstitutesAllergieses();
        List<SurveyAndTestData> surveyAndTestDatas = allergies.getSurveyAndTestDatas();
        List<SynonymAllergies> synonymAllergieses = allergies.getSynonymAllergieses();
        if(compoundsAllergieses != null && Hibernate.isInitialized(compoundsAllergieses)) {
            compoundsAllergieses.forEach(_compoundsAllergies -> _compoundsAllergies.setAllergies(allergies));
        }
        if(substitutesAllergieses != null && Hibernate.isInitialized(substitutesAllergieses)) {
            substitutesAllergieses.forEach(_substitutesAllergies -> _substitutesAllergies.setAllergies(allergies));
        }
        if(surveyAndTestDatas != null && Hibernate.isInitialized(surveyAndTestDatas)) {
            surveyAndTestDatas.forEach(_surveyAndTestData -> _surveyAndTestData.setAllergies(allergies));
        }
        if(synonymAllergieses != null && Hibernate.isInitialized(synonymAllergieses)) {
            synonymAllergieses.forEach(_synonymAllergies -> _synonymAllergies.setAllergies(allergies));
        }

        Allergies allergiesCreated = this.wmGenericDao.create(allergies);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(allergiesCreated);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public Allergies getById(Integer allergiesId) {
        LOGGER.debug("Finding Allergies by id: {}", allergiesId);
        return this.wmGenericDao.findById(allergiesId);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public Allergies findById(Integer allergiesId) {
        LOGGER.debug("Finding Allergies by id: {}", allergiesId);
        try {
            return this.wmGenericDao.findById(allergiesId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Allergies found with id: {}", allergiesId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public List<Allergies> findByMultipleIds(List<Integer> allergiesIds, boolean orderedReturn) {
        LOGGER.debug("Finding Allergies by ids: {}", allergiesIds);

        return this.wmGenericDao.findByMultipleIds(allergiesIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "medidataTransactionManager")
    @Override
    public Allergies update(Allergies allergies) {
        LOGGER.debug("Updating Allergies with information: {}", allergies);

        List<CompoundsAllergies> compoundsAllergieses = allergies.getCompoundsAllergieses();
        List<SubstitutesAllergies> substitutesAllergieses = allergies.getSubstitutesAllergieses();
        List<SurveyAndTestData> surveyAndTestDatas = allergies.getSurveyAndTestDatas();
        List<SynonymAllergies> synonymAllergieses = allergies.getSynonymAllergieses();
        if(compoundsAllergieses != null && Hibernate.isInitialized(compoundsAllergieses)) {
            compoundsAllergieses.forEach(_compoundsAllergies -> _compoundsAllergies.setAllergies(allergies));
        }
        if(substitutesAllergieses != null && Hibernate.isInitialized(substitutesAllergieses)) {
            substitutesAllergieses.forEach(_substitutesAllergies -> _substitutesAllergies.setAllergies(allergies));
        }
        if(surveyAndTestDatas != null && Hibernate.isInitialized(surveyAndTestDatas)) {
            surveyAndTestDatas.forEach(_surveyAndTestData -> _surveyAndTestData.setAllergies(allergies));
        }
        if(synonymAllergieses != null && Hibernate.isInitialized(synonymAllergieses)) {
            synonymAllergieses.forEach(_synonymAllergies -> _synonymAllergies.setAllergies(allergies));
        }

        this.wmGenericDao.update(allergies);
        this.wmGenericDao.refresh(allergies);

        // Deleting children which are not present in the list.
        if(compoundsAllergieses != null && Hibernate.isInitialized(compoundsAllergieses) && !compoundsAllergieses.isEmpty()) {
            List<CompoundsAllergies> _remainingChildren = wmGenericDao.execute(
                session -> DaoUtils.findAllRemainingChildren(session, CompoundsAllergies.class,
                        new DaoUtils.ChildrenFilter<>("allergies", allergies, compoundsAllergieses)));
            LOGGER.debug("Found {} detached children, deleting", _remainingChildren.size());
            _remainingChildren.forEach(_compoundsAllergies -> compoundsAllergiesService.delete(_compoundsAllergies));
            allergies.setCompoundsAllergieses(compoundsAllergieses);
        }

        // Deleting children which are not present in the list.
        if(substitutesAllergieses != null && Hibernate.isInitialized(substitutesAllergieses) && !substitutesAllergieses.isEmpty()) {
            List<SubstitutesAllergies> _remainingChildren = wmGenericDao.execute(
                session -> DaoUtils.findAllRemainingChildren(session, SubstitutesAllergies.class,
                        new DaoUtils.ChildrenFilter<>("allergies", allergies, substitutesAllergieses)));
            LOGGER.debug("Found {} detached children, deleting", _remainingChildren.size());
            _remainingChildren.forEach(_substitutesAllergies -> substitutesAllergiesService.delete(_substitutesAllergies));
            allergies.setSubstitutesAllergieses(substitutesAllergieses);
        }

        // Deleting children which are not present in the list.
        if(surveyAndTestDatas != null && Hibernate.isInitialized(surveyAndTestDatas) && !surveyAndTestDatas.isEmpty()) {
            List<SurveyAndTestData> _remainingChildren = wmGenericDao.execute(
                session -> DaoUtils.findAllRemainingChildren(session, SurveyAndTestData.class,
                        new DaoUtils.ChildrenFilter<>("allergies", allergies, surveyAndTestDatas)));
            LOGGER.debug("Found {} detached children, deleting", _remainingChildren.size());
            _remainingChildren.forEach(_surveyAndTestData -> surveyAndTestDataService.delete(_surveyAndTestData));
            allergies.setSurveyAndTestDatas(surveyAndTestDatas);
        }

        // Deleting children which are not present in the list.
        if(synonymAllergieses != null && Hibernate.isInitialized(synonymAllergieses) && !synonymAllergieses.isEmpty()) {
            List<SynonymAllergies> _remainingChildren = wmGenericDao.execute(
                session -> DaoUtils.findAllRemainingChildren(session, SynonymAllergies.class,
                        new DaoUtils.ChildrenFilter<>("allergies", allergies, synonymAllergieses)));
            LOGGER.debug("Found {} detached children, deleting", _remainingChildren.size());
            _remainingChildren.forEach(_synonymAllergies -> synonymAllergiesService.delete(_synonymAllergies));
            allergies.setSynonymAllergieses(synonymAllergieses);
        }

        return allergies;
    }

    @Transactional(value = "medidataTransactionManager")
    @Override
    public Allergies delete(Integer allergiesId) {
        LOGGER.debug("Deleting Allergies with id: {}", allergiesId);
        Allergies deleted = this.wmGenericDao.findById(allergiesId);
        if (deleted == null) {
            LOGGER.debug("No Allergies found with id: {}", allergiesId);
            throw new EntityNotFoundException(String.valueOf(allergiesId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "medidataTransactionManager")
    @Override
    public void delete(Allergies allergies) {
        LOGGER.debug("Deleting Allergies with {}", allergies);
        this.wmGenericDao.delete(allergies);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public Page<Allergies> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Allergies");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public Page<Allergies> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Allergies");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service medidata for table Allergies to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service medidata for table Allergies to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public Page<CompoundsAllergies> findAssociatedCompoundsAllergieses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated compoundsAllergieses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("allergies.id = '" + id + "'");

        return compoundsAllergiesService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public Page<SubstitutesAllergies> findAssociatedSubstitutesAllergieses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated substitutesAllergieses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("allergies.id = '" + id + "'");

        return substitutesAllergiesService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public Page<SurveyAndTestData> findAssociatedSurveyAndTestDatas(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated surveyAndTestDatas");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("allergies.id = '" + id + "'");

        return surveyAndTestDataService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "medidataTransactionManager")
    @Override
    public Page<SynonymAllergies> findAssociatedSynonymAllergieses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated synonymAllergieses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("allergies.id = '" + id + "'");

        return synonymAllergiesService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service CompoundsAllergiesService instance
     */
    protected void setCompoundsAllergiesService(CompoundsAllergiesService service) {
        this.compoundsAllergiesService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service SubstitutesAllergiesService instance
     */
    protected void setSubstitutesAllergiesService(SubstitutesAllergiesService service) {
        this.substitutesAllergiesService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service SurveyAndTestDataService instance
     */
    protected void setSurveyAndTestDataService(SurveyAndTestDataService service) {
        this.surveyAndTestDataService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service SynonymAllergiesService instance
     */
    protected void setSynonymAllergiesService(SynonymAllergiesService service) {
        this.synonymAllergiesService = service;
    }

}