/*Copyright (c) 2018-2019 medidesign.co.uk All Rights Reserved.
 This software is the confidential and proprietary information of medidesign.co.uk You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medidesign.co.uk*/
package com.dotta.medidata.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.dotta.medidata.SurveyUnique;
import com.dotta.medidata.SurveyUniqueId;

/**
 * Service object for domain model class {@link SurveyUnique}.
 */
public interface SurveyUniqueService {

    /**
     * Creates a new SurveyUnique. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on SurveyUnique if any.
     *
     * @param surveyUnique Details of the SurveyUnique to be created; value cannot be null.
     * @return The newly created SurveyUnique.
     */
    SurveyUnique create(@Valid SurveyUnique surveyUnique);


	/**
     * Returns SurveyUnique by given id if exists.
     *
     * @param surveyuniqueId The id of the SurveyUnique to get; value cannot be null.
     * @return SurveyUnique associated with the given surveyuniqueId.
	 * @throws EntityNotFoundException If no SurveyUnique is found.
     */
    SurveyUnique getById(SurveyUniqueId surveyuniqueId);

    /**
     * Find and return the SurveyUnique by given id if exists, returns null otherwise.
     *
     * @param surveyuniqueId The id of the SurveyUnique to get; value cannot be null.
     * @return SurveyUnique associated with the given surveyuniqueId.
     */
    SurveyUnique findById(SurveyUniqueId surveyuniqueId);

	/**
     * Find and return the list of SurveyUniques by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param surveyuniqueIds The id's of the SurveyUnique to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return SurveyUniques associated with the given surveyuniqueIds.
     */
    List<SurveyUnique> findByMultipleIds(List<SurveyUniqueId> surveyuniqueIds, boolean orderedReturn);


    /**
     * Updates the details of an existing SurveyUnique. It replaces all fields of the existing SurveyUnique with the given surveyUnique.
     *
     * This method overrides the input field values using Server side or database managed properties defined on SurveyUnique if any.
     *
     * @param surveyUnique The details of the SurveyUnique to be updated; value cannot be null.
     * @return The updated SurveyUnique.
     * @throws EntityNotFoundException if no SurveyUnique is found with given input.
     */
    SurveyUnique update(@Valid SurveyUnique surveyUnique);

    /**
     * Deletes an existing SurveyUnique with the given id.
     *
     * @param surveyuniqueId The id of the SurveyUnique to be deleted; value cannot be null.
     * @return The deleted SurveyUnique.
     * @throws EntityNotFoundException if no SurveyUnique found with the given id.
     */
    SurveyUnique delete(SurveyUniqueId surveyuniqueId);

    /**
     * Deletes an existing SurveyUnique with the given object.
     *
     * @param surveyUnique The instance of the SurveyUnique to be deleted; value cannot be null.
     */
    void delete(SurveyUnique surveyUnique);

    /**
     * Find all SurveyUniques matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SurveyUniques.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<SurveyUnique> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all SurveyUniques matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SurveyUniques.
     *
     * @see Pageable
     * @see Page
     */
    Page<SurveyUnique> findAll(String query, Pageable pageable);

    /**
     * Exports all SurveyUniques matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all SurveyUniques matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the SurveyUniques in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the SurveyUnique.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}