/*Copyright (c) 2018-2019 medidesign.co.uk All Rights Reserved.
 This software is the confidential and proprietary information of medidesign.co.uk You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medidesign.co.uk*/
package com.dotta.medidata;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Background generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`background`", uniqueConstraints = {
            @UniqueConstraint(name = "`id_UNIQUE`", columnNames = {"`id`"})})
@IdClass(BackgroundId.class)
public class Background implements Serializable {

    private Integer patientId;
    private Integer id;
    private int sessionId;
    private String termsAccepted;
    private String priorAllergyTreatment;
    private String ethnicity;
    private String earlyUrbanRural;
    private String earlyPetsLivestock;
    private String olderSiblings;
    private String familyIngestionAllergy;
    private String familyAeroAllergy;
    private String familyContactAllergy;
    private String familyEczema;
    private String familyAsthma;
    private String familyCeliac;
    private String ingestionAllergy;
    private String aeroAllergy;
    private String contactAllergy;
    private String eczema;
    private String asthma;
    private String celiac;
    private String breastfed;
    private String weaned;
    private String cesarian;
    private BigDecimal weight;
    private Patients patients;

    @Id
    @Column(name = "`patient_id`", nullable = false, scale = 0, precision = 10)
    public Integer getPatientId() {
        return this.patientId;
    }

    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    @Id
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`session_id`", nullable = false, scale = 0, precision = 10)
    public int getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }

    @Column(name = "`terms_accepted`", nullable = true, length = 65535)
    public String getTermsAccepted() {
        return this.termsAccepted;
    }

    public void setTermsAccepted(String termsAccepted) {
        this.termsAccepted = termsAccepted;
    }

    @Column(name = "`prior_allergy_treatment`", nullable = true, length = 65535)
    public String getPriorAllergyTreatment() {
        return this.priorAllergyTreatment;
    }

    public void setPriorAllergyTreatment(String priorAllergyTreatment) {
        this.priorAllergyTreatment = priorAllergyTreatment;
    }

    @Column(name = "`ethnicity`", nullable = true, length = 65535)
    public String getEthnicity() {
        return this.ethnicity;
    }

    public void setEthnicity(String ethnicity) {
        this.ethnicity = ethnicity;
    }

    @Column(name = "`early_urban_rural`", nullable = true, length = 65535)
    public String getEarlyUrbanRural() {
        return this.earlyUrbanRural;
    }

    public void setEarlyUrbanRural(String earlyUrbanRural) {
        this.earlyUrbanRural = earlyUrbanRural;
    }

    @Column(name = "`early_pets_livestock`", nullable = true, length = 65535)
    public String getEarlyPetsLivestock() {
        return this.earlyPetsLivestock;
    }

    public void setEarlyPetsLivestock(String earlyPetsLivestock) {
        this.earlyPetsLivestock = earlyPetsLivestock;
    }

    @Column(name = "`older_siblings`", nullable = true, length = 65535)
    public String getOlderSiblings() {
        return this.olderSiblings;
    }

    public void setOlderSiblings(String olderSiblings) {
        this.olderSiblings = olderSiblings;
    }

    @Column(name = "`family_ingestion_allergy`", nullable = true, length = 65535)
    public String getFamilyIngestionAllergy() {
        return this.familyIngestionAllergy;
    }

    public void setFamilyIngestionAllergy(String familyIngestionAllergy) {
        this.familyIngestionAllergy = familyIngestionAllergy;
    }

    @Column(name = "`family_aero_allergy`", nullable = true, length = 65535)
    public String getFamilyAeroAllergy() {
        return this.familyAeroAllergy;
    }

    public void setFamilyAeroAllergy(String familyAeroAllergy) {
        this.familyAeroAllergy = familyAeroAllergy;
    }

    @Column(name = "`family_contact_allergy`", nullable = true, length = 65535)
    public String getFamilyContactAllergy() {
        return this.familyContactAllergy;
    }

    public void setFamilyContactAllergy(String familyContactAllergy) {
        this.familyContactAllergy = familyContactAllergy;
    }

    @Column(name = "`family_eczema`", nullable = true, length = 65535)
    public String getFamilyEczema() {
        return this.familyEczema;
    }

    public void setFamilyEczema(String familyEczema) {
        this.familyEczema = familyEczema;
    }

    @Column(name = "`family_asthma`", nullable = true, length = 65535)
    public String getFamilyAsthma() {
        return this.familyAsthma;
    }

    public void setFamilyAsthma(String familyAsthma) {
        this.familyAsthma = familyAsthma;
    }

    @Column(name = "`family_celiac`", nullable = true, length = 65535)
    public String getFamilyCeliac() {
        return this.familyCeliac;
    }

    public void setFamilyCeliac(String familyCeliac) {
        this.familyCeliac = familyCeliac;
    }

    @Column(name = "`ingestion_allergy`", nullable = true, length = 65535)
    public String getIngestionAllergy() {
        return this.ingestionAllergy;
    }

    public void setIngestionAllergy(String ingestionAllergy) {
        this.ingestionAllergy = ingestionAllergy;
    }

    @Column(name = "`aero_allergy`", nullable = true, length = 65535)
    public String getAeroAllergy() {
        return this.aeroAllergy;
    }

    public void setAeroAllergy(String aeroAllergy) {
        this.aeroAllergy = aeroAllergy;
    }

    @Column(name = "`contact_allergy`", nullable = true, length = 65535)
    public String getContactAllergy() {
        return this.contactAllergy;
    }

    public void setContactAllergy(String contactAllergy) {
        this.contactAllergy = contactAllergy;
    }

    @Column(name = "`eczema`", nullable = true, length = 65535)
    public String getEczema() {
        return this.eczema;
    }

    public void setEczema(String eczema) {
        this.eczema = eczema;
    }

    @Column(name = "`asthma`", nullable = true, length = 65535)
    public String getAsthma() {
        return this.asthma;
    }

    public void setAsthma(String asthma) {
        this.asthma = asthma;
    }

    @Column(name = "`celiac`", nullable = true, length = 65535)
    public String getCeliac() {
        return this.celiac;
    }

    public void setCeliac(String celiac) {
        this.celiac = celiac;
    }

    @Column(name = "`breastfed`", nullable = true, length = 65535)
    public String getBreastfed() {
        return this.breastfed;
    }

    public void setBreastfed(String breastfed) {
        this.breastfed = breastfed;
    }

    @Column(name = "`weaned`", nullable = true, length = 65535)
    public String getWeaned() {
        return this.weaned;
    }

    public void setWeaned(String weaned) {
        this.weaned = weaned;
    }

    @Column(name = "`cesarian`", nullable = true, length = 65535)
    public String getCesarian() {
        return this.cesarian;
    }

    public void setCesarian(String cesarian) {
        this.cesarian = cesarian;
    }

    @Column(name = "`weight`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getWeight() {
        return this.weight;
    }

    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`patient_id`", referencedColumnName = "`id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`fk_background_patients1`"))
    @Fetch(FetchMode.JOIN)
    public Patients getPatients() {
        return this.patients;
    }

    public void setPatients(Patients patients) {
        if(patients != null) {
            this.patientId = patients.getId();
        }

        this.patients = patients;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Background)) return false;
        final Background background = (Background) o;
        return Objects.equals(getPatientId(), background.getPatientId()) &&
                Objects.equals(getId(), background.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPatientId(),
                getId());
    }
}