/*Copyright (c) 2018-2019 medidesign.co.uk All Rights Reserved.
 This software is the confidential and proprietary information of medidesign.co.uk You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medidesign.co.uk*/
package com.dotta.medidata;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProbabilityAllergySymptomPrimary generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`probability_allergy_symptom_primary`")
public class ProbabilityAllergySymptomPrimary implements Serializable {

    private Integer id;
    private int allergyId;
    private int symptomId;
    private int symptomResult;
    private BigDecimal probability;
    private String message;
    private BigDecimal severityAdj;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`allergy_id`", nullable = false, scale = 0, precision = 10)
    public int getAllergyId() {
        return this.allergyId;
    }

    public void setAllergyId(int allergyId) {
        this.allergyId = allergyId;
    }

    @Column(name = "`symptom_id`", nullable = false, scale = 0, precision = 10)
    public int getSymptomId() {
        return this.symptomId;
    }

    public void setSymptomId(int symptomId) {
        this.symptomId = symptomId;
    }

    @Column(name = "`symptom_result`", nullable = false, scale = 0, precision = 10)
    public int getSymptomResult() {
        return this.symptomResult;
    }

    public void setSymptomResult(int symptomResult) {
        this.symptomResult = symptomResult;
    }

    @Column(name = "`probability`", nullable = false, scale = 9, precision = 22)
    public BigDecimal getProbability() {
        return this.probability;
    }

    public void setProbability(BigDecimal probability) {
        this.probability = probability;
    }

    @Column(name = "`message`", nullable = true, length = 65535)
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Column(name = "`severity_adj`", nullable = true, scale = 9, precision = 22)
    public BigDecimal getSeverityAdj() {
        return this.severityAdj;
    }

    public void setSeverityAdj(BigDecimal severityAdj) {
        this.severityAdj = severityAdj;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProbabilityAllergySymptomPrimary)) return false;
        final ProbabilityAllergySymptomPrimary probabilityAllergySymptomPrimary = (ProbabilityAllergySymptomPrimary) o;
        return Objects.equals(getId(), probabilityAllergySymptomPrimary.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}