/*Copyright (c) 2018-2019 medidesign.co.uk All Rights Reserved.
 This software is the confidential and proprietary information of medidesign.co.uk You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medidesign.co.uk*/
package com.dotta.medidata;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SymptomSet generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`symptom_set`")
public class SymptomSet implements Serializable {

    private Integer id;
    private int setId;
    private String symptom;
    private String notes;
    private Integer responseCode;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`set_id`", nullable = false, scale = 0, precision = 10)
    public int getSetId() {
        return this.setId;
    }

    public void setSetId(int setId) {
        this.setId = setId;
    }

    @Column(name = "`symptom`", nullable = false, length = 65535)
    public String getSymptom() {
        return this.symptom;
    }

    public void setSymptom(String symptom) {
        this.symptom = symptom;
    }

    @Column(name = "`notes`", nullable = true, length = 65535)
    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Column(name = "`response_code`", nullable = true, scale = 0, precision = 10)
    public Integer getResponseCode() {
        return this.responseCode;
    }

    public void setResponseCode(Integer responseCode) {
        this.responseCode = responseCode;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SymptomSet)) return false;
        final SymptomSet symptomSet = (SymptomSet) o;
        return Objects.equals(getId(), symptomSet.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}